### PR TITLE
fixes rendering the views with nested dictionaries

### PR DESCRIPTION
**Pull request by clsource**
This is the same code as the working demo

https://github.com/NinjasCL/vapor-inertia-svelte-example

Was not overly tested, but at least it works 👍

### CODE REVIEW

**Comment by clsource** [comment]
ammend. closes #3

**Review by Lloople — CHANGES_REQUESTED** [review]
Awesome work! Could you please leave the readme as a `.md` file? 🙏 Everything else looks fantastic 🎉

**Comment by clsource** [comment]
The adoc format is nearly the same as a markdown.
I change it only because it automatically generates the table of contents.

I could revert it to markdown no problem. But the TOC will be lost.
Is that ok?

**Review by Lloople — APPROVED** [review]

**Comment by clsource** [comment]
it should compile now :)

**Review by Lloople — APPROVED** [review]

**Comment by clsource** [comment]
ok hopefully now it will pass all the tests. I tested locally this time.

**Comment by clsource** [comment]
Thanks 👍

**Pull request merged**
